// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUQnjOj4gjMD3THtCXRN0dARODilfUiW0',
    appId: '1:505152428698:web:a4ee105ac7445695b95d23',
    messagingSenderId: '505152428698',
    projectId: 'gas-agency-app',
    authDomain: 'gas-agency-app.firebaseapp.com',
    storageBucket: 'gas-agency-app.firebasestorage.app',
    measurementId: 'G-R0VXTVSS3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA0RbTD--wWbthmqxogppYQ5Im2IyQfRY',
    appId: '1:505152428698:android:4f456b4ae51558c4b95d23',
    messagingSenderId: '505152428698',
    projectId: 'gas-agency-app',
    storageBucket: 'gas-agency-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7pAZBFBQ3XDlgp3PTRIQ-VvHyIKOXZgk',
    appId: '1:505152428698:ios:ce6515fb567e67a8b95d23',
    messagingSenderId: '505152428698',
    projectId: 'gas-agency-app',
    storageBucket: 'gas-agency-app.firebasestorage.app',
    iosBundleId: 'com.example.gasAgencyIos',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7pAZBFBQ3XDlgp3PTRIQ-VvHyIKOXZgk',
    appId: '1:505152428698:ios:ce6515fb567e67a8b95d23',
    messagingSenderId: '505152428698',
    projectId: 'gas-agency-app',
    storageBucket: 'gas-agency-app.firebasestorage.app',
    iosBundleId: 'com.example.gasAgencyIos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUQnjOj4gjMD3THtCXRN0dARODilfUiW0',
    appId: '1:505152428698:web:3fe8c44451915b23b95d23',
    messagingSenderId: '505152428698',
    projectId: 'gas-agency-app',
    authDomain: 'gas-agency-app.firebaseapp.com',
    storageBucket: 'gas-agency-app.firebasestorage.app',
    measurementId: 'G-XXQR698MBN',
  );
}
